import jsPDF from 'jspdf'
import type { UserStats } from './statsService'
import type { WeaknessPattern } from './weaknessService'

export function generateProgressReport(
    userName: string,
    level: string,
    stats: UserStats,
    weaknesses: WeaknessPattern[]
) {
    const doc = new jsPDF()
    const pageWidth = doc.internal.pageSize.getWidth()
    let y = 20

    // Header
    doc.setFillColor(67, 56, 202) // brand indigo
    doc.rect(0, 0, pageWidth, 35, 'F')
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(20)
    doc.setFont('helvetica', 'bold')
    doc.text('FluentBuddy AI', 15, 20)
    doc.setFontSize(11)
    doc.setFont('helvetica', 'normal')
    doc.text('Learning Progress Report', 15, 28)

    y = 50
    doc.setTextColor(15, 23, 42) // brand slate text
    doc.setFontSize(14)
    doc.setFont('helvetica', 'bold')
    doc.text(`Student: ${userName}`, 15, y)

    y += 7
    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(100, 116, 139)
    doc.text(`Report generated on ${new Date().toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' })}`, 15, y)

    y += 15
    doc.setDrawColor(226, 232, 240)
    doc.line(15, y, pageWidth - 15, y)

    y += 12
    doc.setFontSize(13)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(15, 23, 42)
    doc.text('Overview', 15, y)

    y += 10
    const statBoxes = [
        { label: 'English Level', value: level },
        { label: 'Practice Sessions', value: String(stats.totalConversations) },
        { label: 'Words Learned', value: String(stats.vocabularyCount) },
        { label: 'Grammar Accuracy', value: `${Math.max(0, 100 - stats.totalMistakes * 3)}%` },
    ]

    const boxWidth = (pageWidth - 30 - 15) / 4
    statBoxes.forEach((box, i) => {
        const x = 15 + i * (boxWidth + 5)
        doc.setFillColor(248, 250, 252)
        doc.roundedRect(x, y, boxWidth, 22, 2, 2, 'F')
        doc.setFontSize(8)
        doc.setTextColor(100, 116, 139)
        doc.text(box.label, x + 3, y + 8)
        doc.setFontSize(12)
        doc.setFont('helvetica', 'bold')
        doc.setTextColor(67, 56, 202)
        doc.text(box.value, x + 3, y + 17)
        doc.setFont('helvetica', 'normal')
    })

    y += 35
    doc.setDrawColor(226, 232, 240)
    doc.line(15, y, pageWidth - 15, y)

    y += 12
    doc.setFontSize(13)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(15, 23, 42)
    doc.text('Areas Needing Practice', 15, y)

    y += 8
    if (weaknesses.length === 0) {
        doc.setFontSize(10)
        doc.setFont('helvetica', 'normal')
        doc.setTextColor(100, 116, 139)
        doc.text('No recurring grammar issues detected yet. Keep practicing!', 15, y)
        y += 8
    } else {
        weaknesses.slice(0, 5).forEach((w) => {
            doc.setFontSize(10)
            doc.setFont('helvetica', 'normal')
            doc.setTextColor(51, 65, 85)
            doc.text(`• ${w.topic} — found in ${w.count} message(s)`, 18, y)
            y += 7
        })
    }

    y += 8
    doc.setFontSize(13)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(15, 23, 42)
    doc.text('Recommendation', 15, y)

    y += 8
    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(51, 65, 85)
    const recommendation =
        weaknesses.length > 0
            ? `Focus on practicing "${weaknesses[0].topic}" this week through targeted conversations and the Daily Challenge feature.`
            : 'Continue regular practice to build consistency and expand vocabulary.'
    const splitRec = doc.splitTextToSize(recommendation, pageWidth - 30)
    doc.text(splitRec, 15, y)

    // Footer
    doc.setFontSize(8)
    doc.setTextColor(148, 163, 184)
    doc.text('Generated by FluentBuddy AI — AI/ML Internship Capstone Project', 15, 285)

    doc.save(`FluentBuddy-Progress-Report-${new Date().toISOString().split('T')[0]}.pdf`)
}